


---------------------------------------LAB-13------------------------------------------------------

--Table Has Been Made Using Design Mode--

--1-List all books with their authors.--

SELECT TITLE , AUTHORNAME
FROM BOOK 
INNER JOIN AUTHOR
ON BOOK.AUTHORID = AUTHOR.AUTHORID;

--2-List all books with their publishers.--

SELECT TITLE , PUBLISHERNAME
FROM BOOK 
INNER JOIN PUBLISHER
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID;

--3-List all books with their authors and publishers--

SELECT TITLE , PUBLISHERNAME , AUTHORNAME
FROM BOOK 
INNER JOIN PUBLISHER
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
INNER JOIN AUTHOR
ON BOOK.AUTHORID = AUTHOR.AUTHORID;

--4-List all books published after 2010 with their authors and publisher and price.--

SELECT TITLE , PUBLISHERNAME , AUTHORNAME , PUBLICATIONYEAR , PRICE
FROM BOOK 
INNER JOIN PUBLISHER
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
INNER JOIN AUTHOR
ON BOOK.AUTHORID = AUTHOR.AUTHORID
WHERE PUBLICATIONYEAR > 2010;


--5-List all authors and the number of books they have written.--

SELECT AUTHORNAME , COUNT(BOOKID) AS BOOK_COUNT 
FROM AUTHOR 
INNER JOIN BOOK
ON BOOK.AUTHORID = AUTHOR.AUTHORID
GROUP BY AUTHORNAME;

--6-List all publishers and the total price of books they have published.--

SELECT PUBLISHERNAME , SUM(PRICE) AS TOTAL_PRICE
FROM BOOK 
INNER JOIN PUBLISHER
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
GROUP BY PUBLISHERNAME;

--7-List authors who have not written any books.--

SELECT AUTHORNAME , COUNT(BOOK.AUTHORID) AS TOTAL_BOOOKS
FROM BOOK 
RIGHT OUTER JOIN AUTHOR
ON BOOK.AUTHORID = AUTHOR.AUTHORID
GROUP BY AUTHORNAME
HAVING COUNT(BOOK.AUTHORID) = 0;

--8-Display total number of Books and Average Price of every Author.--

SELECT AUTHORNAME , AVG(PRICE) AS AVG_PRICE , COUNT(BOOK.AUTHORID) AS TOTAL_BOOKS
FROM AUTHOR 
INNER JOIN BOOK
ON BOOK.AUTHORID = AUTHOR.AUTHORID
GROUP BY AUTHORNAME;

--9-lists each publisher along with the total number of books they have published, sorted from highest to 
--lowest. --

SELECT PUBLISHERNAME , COUNT(BOOK.PUBLISHERID) AS TOTAL_BOOOKS
FROM BOOK 
INNER JOIN PUBLISHER
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
GROUP BY PUBLISHERNAME
ORDER BY COUNT(BOOK.PUBLISHERID) DESC;

--10-Display number of books published each year.--

SELECT COUNT(BOOKID) AS TOTAL_BOOKS , PUBLICATIONYEAR
FROM BOOK
GROUP BY PUBLICATIONYEAR;
