--LAB-4--

CREATE TABLE CRICKET(NAME VARCHAR(50),CITY VARCHAR(30),AGE INT);

INSERT INTO CRICKET(NAME , CITY , AGE ) VALUES ('SACHIN TENDULKAR' , 'MUMBAI' ,30);
INSERT INTO CRICKET(NAME , CITY , AGE ) VALUES ('RAHUL DRAVID' , 'BOMBAY' ,35);
INSERT INTO CRICKET(NAME , CITY , AGE ) VALUES ('M.S. DHONI' , 'JARKHAND' ,31);
INSERT INTO CRICKET(NAME , CITY , AGE ) VALUES ('SURESH RAINA' ,	'GUJARAT' ,30);

SELECT* FROM CRICKET;


--1-Create table Worldcup from cricket with all the columns and data.

SELECT *
INTO WORLDCUP
FROM CRICKET
WHERE 1=1;

SELECT* FROM WORLDCUP;


--2-Create table T20 from cricket with first two columns with no data.


SELECT TOP 2*
INTO T20
FROM CRICKET
WHERE 1=0;

SELECT* FROM T20;



--3-Create table IPL From Cricket with No Data.

SELECT *
INTO IPL
FROM CRICKET
WHERE 1=0;

SELECT* FROM IPL;



